beta: 0.001
brush_info_file: settings/my_simple_brush.myb
conditional: false
emnist_gz_images: tmp/emnist_gzip/emnist-letters-train-images-idx3-ubyte.gz
emnist_gz_labels: tmp/emnist_gzip/emnist-letters-train-labels-idx1-ubyte.gz
emnist_single_label: false
empty_drawing_penalty: 10.0
eval_n_runs: 1
gamma: 0.99
gp_lambda: 10.0
imsize: 64
in_channel: 1
jikei_npz: tmp/jikei_dataset_limited.npz
lambda_R: 1.0
lr: 0.0001
max_episode_steps: 10
mnist_binarization: false
mnist_target_label: null
n_eval_interval: 10
n_save_final_obs_interval: 10
n_save_interval: 30
n_update: 10000000000000000
pos_resolution: 32
problem: mnist
processes: 12
quickdraw_npz: tmp/quickdraw_apple.npz
reward_mode: wgangp
rollout_n: 20
seed: 0
staying_penalty: 0.0
weight_decay: 0.0
